variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

build-job:
  stage: build
  image: node:20-alpine
  tags: 
    - docker
  script:
    - npm ci
    - npm run build
  artifacts:
    expire_in: 1 hour
    paths:
      - .next/
      - node_modules/
      - public/

run_tests:
  stage: test
  image: node:20-alpine
  tags:
    - docker
  script:
    - npm test

deploy-job:
  stage: deploy
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  tags: 
    - docker
  environment: production
  script:
    - docker compose down --remove-orphans
    - docker compose up -d --build
  only:
    - main