image: docker:24.0.5

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:24.0.5-dind

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - .next/cache/
    - node_modules/

build-frontend:
  stage: build
  image: node:20-alpine
  tags: [docker]
  script:
    - npm ci
    - npm run build
  artifacts:
    expire_in: 1 hour
    paths:
      - .next/
      - public/

lint-frontend:
  stage: test
  image: node:20-alpine
  tags: [docker]
  script:
    - npm ci
    - npm run lint

deploy_to_vercel:
  stage: deploy
  image: node:20-alpine
  needs: ["build-frontend"] 
  script:
    - npm install -g vercel
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
  variables:
    VERCEL_TOKEN: $VERCEL_TOKEN
    VERCEL_ORG_ID: $VERCEL_ORG_ID
    VERCEL_PROJECT_ID: $VERCEL_PROJECT_ID
  only:
    - develop